# This Is Only So I Can Receive Donations Through Patreon 
patreon: SuperBenjaBros

# github: {GitHub Sponsors Username / Max: 4}
# patreon: {Patreon Username / Max: 1}
# open_collective: {Open Collective Username / Max: 1}
# ko_fi: {Ko-fi Username / Max: 1}
# tidelift: {Tidelift Platform Name / Package Name (Eg: SuperBenjaBros/Furry_Proyect) / Max: 1}
# community_bridge: {Community Bridge Project Name (Eg: SuperFurryGame) / Max: 1}
# liberapay: {Liberapay Username / Max: 1}
# issuehunt: {IssueHunt Username / Max: 1}
# lfx_crowdfunding: {Lfx Crowfunding Proyect Name / Max: 1}
# polar: {Polar Username / Max: 1}
# buy_me_a_coffee: {Buy Me A Coffee Username / Max: 1}
# thanks_dev: {Thanks_Dev Username / Max: 1}
# custom: {Url / Max: 4}